package ${packagePath};

/**
 * This entity is generated by code, don't modify it.
 */

<#list imports as imp>
import ${imp};
</#list>

<#list decorators as decor>
${decor}
</#list>
public class ${name} implements Serializable {
  <#list properties as prop>
  <#list prop.decorators as decor>
  ${decor}
  </#list>
  private ${prop.type} ${prop.name};
  </#list>

  private static final long serialVersionUID = 1L;

  <#list properties as prop>
  public ${prop.type} get${prop.name?cap_first}() {
    return ${prop.name};
  }

  public void set${prop.name?cap_first}(${prop.type} ${prop.name}) {
    this.${prop.name} = ${prop.name};
  }

  </#list>
  @Override
  public boolean equals(Object o) {
    if (this == o) return true;
    if (o == null || getClass() != o.getClass()) return false;

    ${name} that = (${name}) o;
    <#list properties as prop><#assign types = ['char', 'int', 'boolean']>
    <#if types?seq_contains(prop.type)>
    if (${prop.name} != that.${prop.name}) return false;
    <#else>
    if (${prop.name} != null ? !${prop.name}.equals(that.${prop.name}) : that.${prop.name} != null) return false;
    </#if>
    </#list>
    return true;
  }

  @Override
  public int hashCode() {
    int result = 0;
    <#list properties as prop>
    <#if prop.type == 'char'>
    result = 31 * result + (int) ${prop.name};
    <#elseif prop.type == 'int'>
    result = 31 * result + ${prop.name};
    <#elseif prop.type == 'boolean'>
    result = 31 * result + (${prop.name} ? 1 : 0);
    <#else>
    result = 31 * result + (${prop.name} != null ? ${prop.name}.hashCode() : 0);
    </#if>
    </#list>
    return result;
  }
}